image: docker:latest

services:
  - docker:dind

stages:
  - build

before_script:
  - mkdir $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json


server:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $USER -p $TOKEN
    - docker build -t $CI_REGISTRY_IMAGE:GrpcDemo.Server -f src/GrpcDemo.Server/Dockerfile .
    - export VERSION=$(date +%y-%m-%d)
    - export TAG=token-${VERSION}-${CI_COMMIT_SHA:0:8}
    - docker tag $CI_REGISTRY_IMAGE:token $CI_REGISTRY_IMAGE:$TAG
    - docker push $CI_REGISTRY_IMAGE:$TAG
  
  when: on_success


client:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $USER -p $TOKEN
    - docker build -t $CI_REGISTRY_IMAGE:GrpcDemo.Client -f src/GrpcDemo.Client/Dockerfile .
    - export VERSION=$(date +%y-%m-%d)
    - export TAG=token-${VERSION}-${CI_COMMIT_SHA:0:8}
    - docker tag $CI_REGISTRY_IMAGE:token $CI_REGISTRY_IMAGE:$TAG
    - docker push $CI_REGISTRY_IMAGE:$TAG

  when: on_success

