image: docker:latest

services:
  - docker:dind

stages:
  - build

before_script:
  - mkdir $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json


server:
  stage: build
  script:
    - docker login $DEV_REGISTRY -u $DEV_REGISTRY_USER -p $DEV_REGISTRY_TOKEN
    - export PROJECT_NAME=$(echo ${CI_PROJECT_NAME} | awk '{print tolower($0)}')
    - export DEVTAG=${DEV_REGISTRY}/${PROJECT_NAME}.server
    - docker build -t $DEVTAG -f ServerDockerfile .
    - docker push $DEVTAG
  
  when: on_success


client:
  stage: build
  script:
    - docker login $DEV_REGISTRY -u $DEV_REGISTRY_USER -p $DEV_REGISTRY_TOKEN
    - export PROJECT_NAME=$(echo ${CI_PROJECT_NAME} | awk '{print tolower($0)}')
    - export DEVTAG=${DEV_REGISTRY}/${PROJECT_NAME}.client
    - docker build -t $DEVTAG -f ClientDockerfile .
    - docker push $DEVTAG

  when: on_success

