name: Release

on: [workflow_dispatch]

jobs:
  build-test-prep-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
      - name: build and test
        run: |
          dotnet restore
          dotnet build -c Release --no-restore
          dotnet test -c Release --no-build
      - name: setup semantic-release
        run: |
          npm install -D semantic-release
          npm install -D @semantic-release/git
          npm install -D @semantic-release/changelog
          npm install -D @semantic-release/exec
          npm install -D semantic-release-dotnet
          npm install -D conventional-changelog-conventionalcommits
          npm install -D semantic-release-telegram-bot
      - name: run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: 5776156426:AAFc9rkOPAVBongjzNhYKRNIJT2fsSuOwnA
          SEMANTIC_RELEASE_PACKAGE: ${{ github.event.repository.name }}
        run: npx semantic-release